offboard_pid_control:
  ros__parameters:
    VK_p: 8.5
    AK_p: 1.7
    Kp_r: 3.5
    Kd_r: 1.45
    Ki_r: 0.0
    Kp_p: 3.5
    Kd_p: 1.45
    Ki_p: 0.0
    Kp_y: 1.0
    Kd_y: 0.1
    Ki_y: 0.0
    Kt: 1.25
    I_max: 0.5
    mass: 3.14
    HOOVER: 0.70